### ISSUE TITLE
Shinytest2 supports ui.R and server.R

### ISSUE THREAD

**Issue by schloerke** [IndrajeetPatil/intro-to-snapshot-testing#1]
> Separating the app into `ui.R` and `server.R` files won't work with `{shinytest2}`.

Near line 729, this should be supported. If it is not, please file an issue. Thank you!

**Comment by IndrajeetPatil** [comment]
Thanks for the quick feedback!

I have created [issue](https://github.com/rstudio/shinytest2/issues/244) to track this.

I am also removing that callout block, since if it is supported, this is likely to be a local issue.
